# docker-compose.yml

version: '2.24.5'

services:
  mongodb:
    image: mongo:4.4.29-focal
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./db:/data/db
    
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb

  flask-app:
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    environment:
      MONGO_USERNAME: admin
      MONGO_PASSWORD: secret